packages:
  - 'packages/*'
  - 'examples/*'
allowBuilds:
  '@biomejs/biome': true
  esbuild: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
minimumReleaseAgeExclude:
  - '@tanstack/query-core@5.101.3'
  - '@tanstack/react-query@5.101.3'
