blank_issues_enabled: false
contact_links:
  - name: Question / discussion
    url: https://github.com/developerEhsan/api-client/discussions
    about: Ask questions and discuss ideas in GitHub Discussions.
