/**
 * React Query hooks emitter (roadmap E5). Emits the source for a
 * `generated/api.hooks.ts` file: one typed `use…` hook per operation, wrapping
 * the TanStack Query integration's `queryOptions` / `mutationOptions` /
 * `infiniteQueryOptions` factories.
 *
 * GET operations become `useQuery` hooks (paginated ones also get a
 * `use…Infinite` variant); every other verb becomes a `useMutation` hook. Names
 * match `api.modules.ts` exactly (`use` + PascalCase(module) + PascalCase(method)),
 * so the wrapped `q.<module>.<kind>.<method>` references always resolve.
 *
 * This is a standalone emitter (not part of the default `generate()` output),
 * since it requires the consumer to choose a query-integration import path.
 */
import type { SchemaAST } from '../types/openapi.types';
import { type EmitModulesOptions, deriveMethodName, resolveModuleName } from './moduleEmitter';

/** Options for {@link emitReactQueryHooks}. */
export interface EmitHooksOptions extends EmitModulesOptions {
  /**
   * Import specifier for the query integration `q`
   * (`createQueryIntegration(...)`). @default './query'
   */
  integrationImport?: string;
  /** Package the React Query hooks come from. @default '@tanstack/react-query' */
  reactQueryImport?: string;
}

function upperFirst(s: string): string {
  return s.length === 0 ? s : s[0]!.toUpperCase() + s.slice(1);
}

function banner(ast: SchemaAST, opts: EmitHooksOptions): string {
  const lines = [
    '/**',
    ' * AUTO-GENERATED by @developerehsan/api-client. DO NOT EDIT.',
    ' *',
    ` * React Query hooks for ${ast.info.title} v${ast.info.version}.`,
  ];
  if (opts.generatedAt) lines.push(` * Generated at: ${opts.generatedAt}`);
  if (opts.sourceHash) lines.push(` * Source hash: ${opts.sourceHash}`);
  lines.push(' */');
  return lines.join('\n');
}

/**
 * Emit the source for `generated/api.hooks.ts`.
 *
 * @example
 * import { parseOpenApi, emitReactQueryHooks } from '@developerehsan/api-client/codegen'
 * import { readFileSync, writeFileSync } from 'node:fs'
 *
 * const ast = parseOpenApi(JSON.parse(readFileSync('./openapi.json', 'utf8')))
 * const src = emitReactQueryHooks(ast, { integrationImport: './query' })
 * writeFileSync('./src/generated/api.hooks.ts', src)
 * // -> export function useProductsGetProductById(params, options) { ... useQuery(...) }
 */
export function emitReactQueryHooks(ast: SchemaAST, opts: EmitHooksOptions = {}): string {
  const integrationImport = opts.integrationImport ?? './query';
  const reactQueryImport = opts.reactQueryImport ?? '@tanstack/react-query';

  const hooks: string[] = [];
  for (const tag of Object.keys(ast.tags).sort()) {
    const { name: moduleName } = resolveModuleName(tag);
    const modPascal = upperFirst(moduleName);
    const seen = new Set<string>();

    for (const opId of [...(ast.tags[tag] ?? [])].sort()) {
      const op = ast.operations[opId];
      if (!op) continue;
      let method = deriveMethodName(opId, tag);
      // Mirror api.modules.ts de-duplication so names line up.
      let unique = method;
      let n = 2;
      while (seen.has(unique)) unique = `${method}${n++}`;
      method = unique;
      seen.add(method);

      const methodPascal = upperFirst(method);
      const q = `q.${moduleName}`;
      const isGet = op.method === 'GET';

      if (isGet) {
        hooks.push(
          `export function use${modPascal}${methodPascal}(\n` +
            `  params?: Parameters<typeof ${q}.queryOptions.${method}>[0],\n` +
            `  options?: { enabled?: boolean },\n` +
            `) {\n` +
            `  return useQuery({ ...${q}.queryOptions.${method}(params), ...options })\n` +
            `}`,
        );
        if (op.isPaginated) {
          hooks.push(
            `export function use${modPascal}${methodPascal}Infinite(\n` +
              `  params?: Parameters<typeof ${q}.infiniteQueryOptions.${method}>[0],\n` +
              `) {\n` +
              `  return useInfiniteQuery(${q}.infiniteQueryOptions.${method}(params))\n` +
              `}`,
          );
        }
      } else {
        hooks.push(
          `export function use${modPascal}${methodPascal}(\n` +
            `  options?: Parameters<typeof ${q}.mutationOptions.${method}>[0],\n` +
            `) {\n` +
            `  return useMutation(${q}.mutationOptions.${method}(options))\n` +
            `}`,
        );
      }
    }
  }

  const imports =
    `import { useQuery, useMutation, useInfiniteQuery } from ${JSON.stringify(reactQueryImport)}\n` +
    `import { q } from ${JSON.stringify(integrationImport)}\n`;

  return `${banner(ast, opts)}\n\n${imports}\n${hooks.join('\n\n')}\n`;
}
